# Generated by Django 6.0 on 2026-02-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skin_concerns',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
